### ISSUE TITLE
bitbake core-image-minimal error

### ISSUE THREAD

**Issue by r4t31** [leon-anavi/meta-rauc-community#10]
ERROR: core-image-minimal-1.0-r0 do_image_wic: No kickstart files from WKS_FILES were found: sdimage-dual-raspberrypi.wks core-image-minimal.wks. Please set WKS_FILE or WKS_FILES appropriately.
ERROR: core-image-minimal-1.0-r0 do_image_wic: Execution of '/home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-minimal/1.0-r0/temp/run.do_image_wic.28073' failed with exit code 1:
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-minimal/1.0-r0/temp/log.do_image_wic.28073
ERROR: Task (/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-core/images/core-image-minimal.bb:do_image_wic) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2409 tasks of which 1 didn't need to be rerun and 1 failed.

DEBUG: Executing python function set_image_size
DEBUG: 70049.200000 = 53884 * 1.300000
DEBUG: 74145.200000 = max(70049.200000, 8192)[70049.200000] + 4096
DEBUG: 74146.000000 = int(74145.200000)
DEBUG: 77824 = aligned(74146)
DEBUG: returning 77824
DEBUG: Python function set_image_size finished
DEBUG: Executing python function extend_recipe_sysroot
NOTE: Direct dependencies are ['virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-core/update-rc.d/update-rc.d_0.8.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-extended/bc/bc_1.07.1.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-extended/parted/parted_3.3.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-kernel/kmod/kmod-native_git.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/mtools/mtools_4.0.23.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/fdisk/gptfdisk_1.0.4.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/btrfs-tools/btrfs-tools_5.4.1.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-extended/xz/xz_5.2.4.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-support/bmap-tools/bmap-tools_3.5.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/opkg/opkg_0.4.2.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/dosfstools/dosfstools_4.1.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-core/glibc/glibc_2.31.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/gcc/gcc-runtime_9.3.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/gcc/gcc-cross_9.3.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-connectivity/openssl/openssl_1.1.1i.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/flex/flex_2.6.4.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/bison/bison_3.5.4.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-support/lzop/lzop_1.04.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-bsp/u-boot/u-boot-tools_2020.01.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/cdrtools/cdrtools-native_3.01.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/opkg-utils/opkg-utils_0.4.2.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/syslinux/syslinux_6.04-pre2.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-kernel/dtc/dtc_1.6.0.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-kernel/kern-tools/kern-tools-native_git.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/qemu/qemuwrapper-cross_1.0.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-extended/pigz/pigz_2.4.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-core/glibc/cross-localedef-native_2.31.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/swig/swig_3.0.12.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-extended/pbzip2/pbzip2_1.1.13.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/squashfs-tools/squashfs-tools_git.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/makedevs/makedevs_1.0.1.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/binutils/binutils-cross_2.34.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/e2fsprogs/e2fsprogs_1.45.4.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-core/glibc/ldconfig-native_2.12.1.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta-raspberrypi/recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-kernel/kmod/depmodwrapper-cross_1.0.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bb:do_populate_sysroot', 'virtual:native:/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/python/python3_3.8.2.bb:do_populate_sysroot', '/home/rat/rauc_raspberry/poky-rpi-rauc/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot']
NOTE: Installed into sysroot: ['bc-native', 'parted-native', 'rpi-config', 'gptfdisk-native', 'dosfstools-native', 'glibc', 'gcc-runtime', 'gcc-cross-arm', 'flex-native', 'bison-native', 'lzop-native', 'u-boot-tools-native', 'dtc-native', 'kern-tools-native', 'swig-native', 'binutils-cross-arm', 'rpi-u-boot-scr', 'linux-raspberrypi', 'popt-native', 'linux-libc-headers', 'libgcc', 'libmpc-native', 'gmp-native', 'mpfr-native']
NOTE: Skipping as already exists in sysroot: ['update-rc.d-native', 'patch-native', 'pseudo-native', 'kmod-native', 'mtools-native', 'btrfs-tools-native', 'xz-native', 'bmap-tools-native', 'opkg-native', 'openssl-native', 'cdrtools-native', 'opkg-utils-native', 'syslinux-native', 'qemuwrapper-cross', 'pigz-native', 'cross-localedef-native', 'pbzip2-native', 'squashfs-tools-native', 'makedevs-native', 'e2fsprogs-native', 'ldconfig-native', 'depmodwrapper-cross', 'python3-native', 'quilt-native', 'debianutils-native', 'readline-native', 'automake-native', 'gnu-config-native', 'texinfo-dummy-native', 'libtool-native', 'autoconf-native', 'ncurses-native', 'util-linux-native', 'gettext-minimal-native', 'pkgconfig-native', 'attr-native', 'gtk-doc-native', 'zlib-native', 'systemd-systemctl-native', 'shared-mime-info-native', 'lzo-native', 'python3-setuptools-native', 'acl-native', 'python3-six-native', 'libarchive-native', 'libsolv-native', 'shadow-native', 'perl-native', 'nasm-native', 'm4-native', 'qemu-native', 'libpcre-native', 'bzip2-native', 'lz4-native', 'gdbm-native', 'sqlite3-native', 'libffi-native', 'libtirpc-native', 'libnsl2-native', 'libpcre2-native', 'libcap-ng-native', 'itstool-native', 'glib-2.0-native', 'libxml2-native', 'unzip-native', 'expat-native', 'cmake-native', 'ninja-native', 'db-native', 'groff-native', 'meson-native', 'gettext-native', 'curl-native', 're2c-native']
DEBUG: sed -e 's:^[^/]*/:/home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-minimal/1.0-r0/recipe-sysroot-native/:g' /home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/sysroots-components/x86_64/gcc-cross-arm/fixmepath /home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/sysroots-components/x86_64/bison-native/fixmepath /home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/sysroots-components/x86_64/gmp-native/fixmepath | xargs sed -i -e 's:FIXMESTAGINGDIRTARGET:/home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-minimal/1.0-r0/recipe-sysroot:g; s:FIXMESTAGINGDIRHOST:/home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-minimal/1.0-r0/recipe-sysroot-native:g' -e 's:FIXME_PSEUDO_SYSROOT:/home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/sysroots-components/x86_64/pseudo-native:g' -e 's:FIXME_HOSTTOOLS_DIR:/home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/hosttools:g' -e 's:FIXME_PKGDATA_DIR:/home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/pkgdata/raspberrypi4:g' -e 's:FIXME_PSEUDO_LOCALSTATEDIR:/home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-minimal/1.0-r0/pseudo/:g' -e 's:FIXME_LOGFIFO:/home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-minimal/1.0-r0/temp/fifo.28073:g'
DEBUG: Python function extend_recipe_sysroot finished
DEBUG: Executing shell function do_image_wic
ERROR: No kickstart files from WKS_FILES were found: sdimage-dual-raspberrypi.wks core-image-minimal.wks. Please set WKS_FILE or WKS_FILES appropriately.
WARNING: exit code 1 from a shell command.
ERROR: Execution of '/home/rat/rauc_raspberry/poky-rpi-rauc/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-minimal/1.0-r0/temp/run.do_image_wic.28073' failed with exit code 1:
WARNING: exit code 1 from a shell command.

**Comment by leon-anavi** [comment]
Hi @r4t31,

What is your configuration for `WKS_FILE` in `conf/local.conf` ?

Best regards, Leon

**Comment by r4t31** [comment]
> Hi @r4t31,
> 
> What is your configuration for `WKS_FILE` in `conf/local.conf` ?
> 
> Best regards, Leon

Hello!

WKS_FILE = "sdimage-dual-raspberrypi.wks"

When I rename sdimage-dual-raspberrypi.wks.in to just sdimage-dual-raspberrypi.wks (without io) it compiles normally.
(meta-rauc-raspberrypi/wic)

Can you please help me, how can I run this created image in qemu?

**Comment by leon-anavi** [comment]
Yes, it should be `WKS_FILE = "sdimage-dual-raspberrypi.wks.in"` following the rename of the fine in GitHub PR: https://github.com/leon-anavi/meta-rauc-community/pull/6

As of the moment only Raspberry Pi is supported in this Yocto/OE layer. Further integration and efforts are required for QEMU.

It seems that you have solved the issue with `WKS_FILE` therefore I will close the issue.

Best regards,
Leon

**Comment by r4t31** [comment]
> WKS_FILE = "sdimage-dual-raspberrypi.wks
In your youtube video and presentation WKS_FILE = "sdimage-dual-raspberrypi.wks". 

Can you please advice some other possibility to get RAUC in QEMU?

**Comment by leon-anavi** [comment]
@r4t31 have you tried https://github.com/romainreignier/meta-rauc-qemux86 ?

Best regards, Leon

**Comment by r4t31** [comment]
> @r4t31 have you tried https://github.com/romainreignier/meta-rauc-qemux86 ?
> 
> Best regards, Leon

Unfortunately, I need to run it in ARM... Do exist some way to run ARM applications in qemux86?

**Comment by dev-0x7C6** [comment]
Hi,

Maybe something from https://layers.openembedded.org/layerindex/branch/master/machines/?q=qemu&search=1 ?

Cheers,
Bartłomiej

**Comment by r4t31** [comment]
> Hi,
> 
> Maybe something from https://layers.openembedded.org/layerindex/branch/master/machines/?q=qemu&search=1 ?
> 
> Seems that `qemuarm` is already in openembedded-core.
> 
> Cheers,
> Bartłomiej

Thank you! I know that. But then I try to add RAUC meta layer or compile RAUC in this emulator I always have problems...

**Comment by dev-0x7C6** [comment]
> Thank you! I know that.

Ah, sorry :)

I never tried to use `qemuarm`. I don't even sure what bootloader is used when using with qemu. If there is possibility to run uboot there then `boot.cmd` script maybe useful. 

> Do exist some way to run ARM applications in qemux86

I remember that qemu offers qemu-static-user or something like that. With this I was able to chroot into arm rootfs environment on x86-64 host. Probably this is not great idea to insert qemu-static-user into qemu86 image in order to run arm application (with whole arm rootfs also).

**Comment by r4t31** [comment]
> > Thank you! I know that.
> 
> Ah, sorry :)
> 
> I never tried to use `qemuarm`. I don't even sure what bootloader is used when using with qemu. If there is possibility to run uboot there then `boot.cmd` script maybe useful.
> 
> > Do exist some way to run ARM applications in qemux86
> 
> I remember that qemu offers qemu-static-user or something like that. With this I was able to chroot into arm rootfs environment on x86-64 host. Probably this is not great idea to insert qemu-static-user into qemu86 image in order to run arm application (with whole arm rootfs also).

Thank you for your answer!  If you in future will find some solution, please share it with me!
