### ISSUE TITLE
Blank screen on boot

### ISSUE THREAD

**Issue by alex88** [leon-anavi/meta-rauc-community#13]
Hi there, I've tried to use this layer using these settings:

```
MACHINE=raspberrypi-4
DISTRO_FEATURES_remove ?= "alsa ext2 api-documentation bluetooth ipv6 opengl pcmcia ppp ptest wayland wifi x11 vulkan"
IMAGE_FEATURES += "ssh-server-dropbear"
IMAGE_FEATURES += "debug-tweaks"
IMAGE_INSTALL_append += " nodejs nodejs-npm node-red bash"
DISTRO_FEATURES += "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
ENABLE_UART = "0"
RPI_USE_U_BOOT = "1"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
IMAGE_INSTALL_append += " rauc"
DISTRO_FEATURES += "rauc"
SDIMG_ROOTFS_TYPE = "ext4"
WKS_FILE = "sdimage-dual-raspberrypi.wks.in"
```

I have ENABLE_UART to 0 (tried also without setting it) because I don't have a seria lcable.

Basically the raspberry only shows a blank page, no output or anything. Before adding this layer and using only uboot everything was working, do you have any advice on what to try?

**Comment by leon-anavi** [comment]
Hi @alex88,

I recommend you to enable `ENABLE_UART` and to check the output on the serial console using UART to USB debug cable in order to get better understanding what is going on. Probably the logs from the serial console will indicate the cause of the issue you are having.

Best regards,
Leon

**Comment by alex88** [comment]
Thanks for such a quick response, I'll buy the cable and see what's going on! In the meantime I'll try also other bootloaders

**Comment by leon-anavi** [comment]
@alex88 the RAUC integration having depends on u-boot. 

Btw details how to use the layer are available here: https://www.konsulko.com/getting-started-with-rauc-on-raspberry-pi-2/#comment-334 with a minor that it should be `WKS_FILE = "sdimage-dual-raspberrypi.wks.in"`.

**Comment by alex88** [comment]
Yeah that's the one I've followed, the only difference is that the machine was set to 64 bit. Thanks!

**Comment by leon-anavi** [comment]
this might be related to the issue you are experience. If you ask me, you better make sure you have it working as per tutorial before proceeding with any changes.

Best regards,
Leon

**Comment by alex88** [comment]
It looked simple enough at first, but it seems none of this is simple at least at first

**Comment by alex88** [comment]
The 32 bit version works just fine, must be an issue with the 64 one, I'll use 32 until the uart cable gets delivered and then maybe spend some time with the 64 one. I saw there are some issues for the 64bit version on the meta-raspberry layer too so I think I can close this issue as it's not related to this layer. Thank you for helping!
