### ISSUE TITLE
yocto build error in do_image_wic phase (no kickstart files found)

### ISSUE THREAD

**Issue by mibcat** [leon-anavi/meta-rauc-community#16]
HI Leon,

I'm following your guide on [Getting Started with RAUC on Raspberry Pi](https://www.konsulko.com/getting-started-with-rauc-on-raspberry-pi-2/) but struggling over a build error:

```bash
ERROR: core-image-minimal-1.0-r0 do_image_wic: No kickstart files from WKS_FILES were found: sdimage-dual-raspberrypi.wks. Please set WKS_FILE or WKS_FILES appropriately.
```

The local conf file contains the line
```
WKS_FILE = "sdimage-dual-raspberrypi.wks"
```

I found the file as "sdimage-dual-raspberrypi.wks.**in**"
![image](https://user-images.githubusercontent.com/3083162/118784297-2f1a8280-b890-11eb-9fc3-475397bc9482.png)

All repositories are on branch dunfell:
```bash
> vcs branch
.....
=== ./meta-openembedded (git) ===
dunfell
=== ./meta-raspberrypi (git) ===
dunfell
=== ./meta-rauc (git) ===
dunfell
=== ./meta-rauc-community (git) ===
dunfell
=== ./poky (git) ===
dunfell
```

I'm not very familiar with Yocto. So could you please give a hint to solve that problem.

Thanks a lot !

Best regards,
Michael.

**Comment by leon-anavi** [comment]
Hi Michael,

Ah, sorry, over the time `sdimage-dual-raspberrypi.wks` was renamed to `sdimage-dual-raspberrypi.wks.in`. Could you please update `WKS_FILE` in your `local.conf` files as the one below?

```
WKS_FILE = "sdimage-dual-raspberrypi.wks.in"
```

I hope this will solved the issue you are experiencing. 

Best regards,
Leon

**Comment by mibcat** [comment]
Indeed this solves the issue - thank you very much for the fast help
(and sorry for not testing it on my own - never thought the solution would be so self-evident :smiley:  )
