### ISSUE TITLE
Create a data partition

### ISSUE THREAD

**Issue by om26er** [leon-anavi/meta-rauc-community#4]
Currently the wks file, creates a boot partition and a set of A/B partitions. We should have a fourth partition for user data as well. Ideally it would auto expand on first boot to "claim" all the remaining sdcard space.

**Comment by dev-0x7C6** [comment]
I'm also using 4th partition for data sharing (`/home`), this is my [solution](https://github.com/dev-0x7C6/meta-retro/blob/master/wic/sdimage-dual-raspberrypi-retro.wks.in) as example. I think that recent version of systemd introduced systemd-reparted that may be configured to resize data partition after first boot.

**Comment by leon-anavi** [comment]
Hi @om26er, @dev-0x7C6,

This is definitely an excellent idea as it will extend the RAUC example that this layer provides.

Thanks,
Leon

**Comment by om26er** [comment]
Should be fixed by https://github.com/leon-anavi/meta-rauc-community/pull/6

**Comment by leon-anavi** [comment]
Hi @om26er,

Thank you for your contribution. I has been merged in master therefore I will close this issue.

Best regards,
Leon
