### ISSUE TITLE
Cannot install rauc image

### ISSUE THREAD

**Issue by HenryGiraldo** [leon-anavi/meta-rauc-community#5]
Hi @leon-anavi , I am trying to use your layer on my rpi4 but I cannot install the rauc file.

Using dunfell branch unmodified, based on core-image-full-cmd.
```
100% Installing failed.
LastError: Failed mounting bundle: failed to run mount: Child process exited with code 32
```
The failure is due I have missing squashfs:
```
Nov 05 12:32:54 raspberrypi4 rauc[195]: Verifying bundle...
Nov 05 12:32:54 raspberrypi4 rauc[195]: Mounting bundle '/tmp/update-bundle-raspberrypi4-20201105092945.raucb' to '/run/rauc/bundle'
Nov 05 12:32:54 raspberrypi4 rauc[381]: mount: /run/rauc/bundle: unknown filesystem type 'squashfs'.
Nov 05 12:32:54 raspberrypi4 rauc[195]: Failed mounting bundle: failed to run mount: Child process exited with code 32
```

I find it strange, should it not have been included as it was added to the rauc.cfg file of the recipes-kernel? or is it that these recipes only apply when an update-bundle is made?

**Comment by HenryGiraldo** [comment]
Adding squashfs to my initial build, it works fine, no issues. I leave the ticket open in case you want to answer the question about the kernel recipes.

**Comment by leon-anavi** [comment]
Hi @HenryGiraldo,

Yes, squashfs is required for RAUC bundles and we have it enabled here: https://github.com/leon-anavi/meta-rauc-community/blob/master/meta-rauc-raspberrypi/recipes-kernel/linux/files/rauc.cfg

On which hardware exactly did you experience this issue?

Best regards,
Leon

**Comment by LeonidLazarev** [comment]
Hello
Looks like the menioned _rauc.cfg_ is not correct. 
In the configuration parameters the prefix **CONFIG_** lost. 
It should look like

_CONFIG_SQUASHFS=y
CONFIG_BLK_DEV_LOOP=y
CONFIG_SQUASHFS_FILE_CACHE=y
CONFIG_SQUASHFS_DECOMP_SINGLE=y
CONFIG_SQUASHFS_ZLIB=y
CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE=3_

Best Regards
Leonid Lazarev

**Comment by leon-anavi** [comment]
Hi @HenryGiraldo, @LeonidLazarev,

Thank you for reporting and suggesting a fix for this bug. I have applied the changes to the master branch and added your credentials to the git commit message trailers.

I've successfully installed RAUC bundle on rpi4 and here is a log to confirm that with this fix SquashFS is enabled:

```
root@raspberrypi4:~# dmesg | grep squash
[    0.889057] squashfs: version 4.0 (2009/01/31) Phillip Lougher
```

Best regards,
Leon
